# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shivangg's Blog
email: xshivangx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Shivangg Tripathi, an electronic tinkerer and enthusiast, studying Electronics and Electrical engineering.
  My aim for writing this blog is to share what I discovered while learning about electronics and automation in general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shivangg.github.io" # the base hostname & protocol for your site
twitter_username: xshivangx
github_username:  shivangg

# Build settings
markdown: kramdown
