# user variables, change this to make custom site.

name: Shivangg's Blog
desc: My weblog to document the stuff I find interesting or challenging so that they may be useful to the community and me in future.
author:
  name: Shivangg
  #avatar: //gravatar.com/avatar/daa1cc36ed2ab0d13045d5cd2431cde9?s=320
  profile: |
    I, Shivang Tripathi, am second year student of Ajay Kumar Garg Engineering College pursuing my Bachelors in Electrical and 
    Electronics engineering. Hailing from the city of Nawabs(Lucknow) ,
     I like learning and exploring into the unknown for anything and everything. I often find myself interested in anything which is even 
     remotely connected to computing systems(Both hardware and software end).

    Currently recruited in the prestigious department of AKGEC,ie, <em>Software Incubator</em>, I plan to learn loads of new stuff everyday like [this mario](mario/index.html) (still developing) from seniors and peers. 
  socials:
    facebook:
    twitter: //twitter.com/xshivangx
    google-plus:
    github: //github.com/shivangg
    stack-overflow: //stackoverflow.com/users/6118172/shivx
    instagram:
    pinterest:
    #steam: //steamcommunity.com/id/neizod/
license: MIT License


# theme variables, change this to make site looks best.
baseurl: 
paginate: 3



# system variables, do not change unless you knew what's it does.
gems: [jekyll-paginate]
paginate_path: page/:num

highlighter: rouge
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed

theme: jekyll-theme-tactile
